dist: trusty
sudo: required
services:
- docker
language: go
go:
  - "1.13.x"

env:
  global:
  - GOFLAGS=-mod=vendor GO111MODULE=on
  - RABBITMQ_ENDPOINT="http://127.0.0.1:15672"
  - RABBITMQ_USERNAME="guest"
  - RABBITMQ_PASSWORD="guest"
  jobs:
  - RABBITMQ_VERSION=3.10
  - RABBITMQ_VERSION=3.9
  - RABBITMQ_VERSION=3.8
  - RABBITMQ_VERSION=3.7

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- make test
- make vet
- docker-compose -f $(pwd)/scripts/docker-compose.yml up -d
- $(pwd)/scripts/wait-rabbitmq-docker.sh
- make testacc
- docker-compose -f $(pwd)/scripts/docker-compose.yml down


branches:
  only:
  - master
  - travis

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
