name: test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rmq_version: ["3.10", "3.11", "3.12", "3.13"]

    env:
      RABBITMQ_VERSION: ${{ matrix.rmq_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: test
        run: make test

      - name: vet
        run: make vet

      - name: testacc
        run: make testacc
