name: Tests

on:
  push:
    branches:
    - develop
    - feature/actions
  pull_request:

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rmq_version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    env:
      RABBITMQ_VERSION: ${{ matrix.rmq_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Tests
        run: make testacc
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Tests
        run: go test -v -cover ./...
  sonar:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}